# Request file sizes
spring:
  servlet:
    multipart:
      max-file-size: 8192KB
      max-request-size: 16384KB


# Swagger springdoc
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method


server:
  port: 8080
  address: localhost

tesseract:
  path: "/usr/share/tessdata/"

logging:
  level:
    org.springframework.web: debug
    org.hibernate: ERROR

#spring.profiles=backUp
#sspring.profiles.active=backUp
#  -tessdata src\main\resources\tessdata