# Request file sizes
spring:
  servlet:
    multipart:
      max-file-size: 8192KB
      max-request-size: 16384KB

# Swagger springdoc
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method


server:
  port: 8086
  address: localhost
  servlet:
    context-path: /api/ocr

tesseract:
  path: "D:/Daniel/Projects/docs-archive-ocr-api/backend/src/main/resources/tessdata"
#  path: "E:/IT-Projects/master_thesis/ocr/docs-archive-ocr-api/backend/src/main/resources/tessdata"
#  path: "src/main/resources/tessdata"

logging:
  level:
    org.springframework.web: debug
    org.hibernate: ERROR

storage:
  controller:
    enabled: true

#spring.profiles=backUp
#sspring.profiles.active=backUp
#  -tessdata src\main\resources\tessdata
